### ISSUE TITLE
CLI does not process scss files

### ISSUE THREAD

**Issue by alexkrolick** [skovhus/css-modules-flow-types#15]
- `css-modules-flow-types src` does not find scss files event though `module.file_ext=.scss
` is set
- changing the extension of the file to `.css` works

**Comment by skovhus** [comment]
Seems we should update the README, but the CLI accept a command line argument `--extension`.

**Comment by MartinCerny-awin** [comment]
Is there option how to pass both css and scss to the argument?

**Comment by skovhus** [comment]
> Is there option how to pass both css and scss to the argument?

No, not currently.

**Comment by skovhus** [comment]
So `css-modules-flow-types src --extension scss` should solve the issue @alexkrolick
