### ISSUE TITLE
Support for strict mode

### ISSUE THREAD

**Issue by soulofmischief** [skovhus/css-modules-flow-types#16]
I want to write a PR to add an option to change the header from `// @flow` to `//@flow strict`.

I've written `strict` as a bool flag in the cli, but I'm not certain of the most idiomatic approach to passing the bool to `printFlowDefinition` since it's in a different package directory.

Is exporting cli  from `css-modules-flow-types-cli` and checking the flag in `css-modules-flow-types-printer` the correct approach, or should the packages be isolated?

**Comment by skovhus** [comment]
> Is exporting cli from css-modules-flow-types-cli and checking the flag in css-modules-flow-types-printer the correct approach, or should the packages be isolated?

That sounds like a good approach. So the printer will accept a flag `flowStrictMode`.

**Comment by soulofmischief** [comment]
I went with the flag `strict` because that made sense as a cli flag, and I wasn't sure how to map `strict` to something like `flowStrictMode` for use in node using meow. Would you prefer the flag `flowStrictMode`?`

**Comment by skovhus** [comment]
> Would you prefer the flag flowStrictMode?

I guess `strict` is fine. 👍

**Comment by skovhus** [comment]
I'm wondering why we don't just change `flow` to `flow strict`, instead of adding a CLI option. Any situation where users don't want strict mode for the generated files?

**Comment by soulofmischief** [comment]
I'm not sure. But I also didn't consider weak mode, either. Maybe a flag, `mode` or something, with `strict`, `weak`, and whatever other modes there might be as the options.

**Comment by soulofmischief** [comment]
I looked into it some more. [Weak mode has been deprecated.](https://github.com/facebook/flow/commit/3fc2a436ce414994ec5e4119f8badcff369da429) Unless you can think of any reason it would be a bad idea, I think your idea of just changing `flow` to `flow strict` is the best solution after all. That doesn't even need a PR, it's a one-liner.

**Comment by skovhus** [comment]
I can’t come up with any reason why we shouldn’t just change it to strict. 

Although it is a one liner, it still deserves a pull request.

**Comment by skovhus** [comment]
Thanks. Released as 1.1.1
