### ISSUE TITLE
Files are not updated/created

### ISSUE THREAD

**Issue by matiasfha** [skovhus/css-modules-flow-types#20]
I added `css-module-flow-types` to work along my `less` files. In the first run the `.less.flow` files were created but in the next run the files are not updated or no new files are created.
The cli script don't show any error.

**Comment by skovhus** [comment]
Thanks for reporting this. Can you create a small reproducible repository or gist?

**Comment by skovhus** [comment]
@matiasfh is this still an issue for you? Then please re-open.
