### ISSUE TITLE
LF CRLF problem

### ISSUE THREAD

**Issue by lunevav** [skovhus/css-modules-flow-types#24]
When using your module both on Unix and Windows It changes EOL separator every time. Can you maybe set EOL based on project files EOL, not on default OS EOL.

**Comment by alexeychikk** [comment]
It would be nice if you use the same EOL as in the first line of the source file, or maybe add appropriate config to the plugin.

**Comment by skovhus** [comment]
Makes sense, it should be easy to add. PRs are more than welcome.
