### ISSUE TITLE
Required module not found

### ISSUE THREAD

**Issue by yachaka** [skovhus/css-modules-flow-types#3]
Hey,

The script is working perfectly, the .flow files are getting correctly generated.
But flow won't pick them up and throws the error 'Required module not found'.
Any idea about why it isn't working?

My files are named `*.scss.module`, I used no `name_mapper` extension on them (I tried with also).
The `.scss.module.flow` files are getting generated but flow is kinda ignoring them.

Thanks for the help!

**Comment by skovhus** [comment]
Sorry, I overlooked this issue. Which version of Flow? Can you try naming one of your files foo.scss (without .module) and see if that works.

**Comment by skovhus** [comment]
@yachaka I cannot reproduce.

**Comment by ndbroadbent** [comment]
@skovhus It's working fine when I use regular `.css`, but I'm also getting "Required module not found" when I use `.scss`. However, the autocomplete is working, so my editor (VSCode) must be picking up all the `.scss.flow` files.

There's just an error at the top of all my components with `import styles from './styles.scss'`, which would be nice to fix. I haven't changed anything in my `.flowconfig`, so I don't know why it would be working with `css` and not `scss`. Should I add a `module.name_mapper` rule to my flow config?

(I'm using `"flow-bin": "^0.53.0"`.)

**Comment by skovhus** [comment]
Where is the error coming from? Is it va code? Which linter?

Does just running Flow from command line give you any errors?

**Comment by ndbroadbent** [comment]
The error is coming from Flow. I'm using eslint, but that doesn't have any issues.

When I run Flow from the command line I get a lot of errors like this:

```
/containers/Container.jsx:21
 21: import styles from './styles.scss'
                        ^^^^^^^^^^^^^^^ ./styles.scss. Required module not found
```

But they don't appear when I use regular CSS.

**Comment by ndbroadbent** [comment]
I can suppress the error by installing [css-module-flow](https://github.com/ckknight/css-module-flow) (just [an empty object with types](https://github.com/ckknight/css-module-flow/blob/master/index.js)), and adding the following to `.flowconfig`:

```
module.name_mapper='^.*\.scss$' -> 'css-module-flow'
```

The error goes away, but then flow doesn't find the `.scss.flow` files that are created by `css-modules-flow-types`.

I have 2 theories about why this might happening:

* Flow has a regex somewhere that only looks for 3 character extensions, so it gets tripped up by `.scss`
* There's a default rule somewhere in Flow that knows about `css`, but doesn't know about `scss`.

But I don't know too much about how `css-modules-flow-types` works. Does the webpack loader just create the `.flow` files, or does it do something else?

One last thing to note is that my `styles.css.flow` and `styles.scss.flow` are identical, so Flow is just getting thrown off by the different extension.

**Comment by ndbroadbent** [comment]
I searched the Flow source code for `css`, and am leaning towards a hard-coded `css` extension. I think [the evidence is in this file](https://github.com/facebook/flow/blob/77c6bed34878a7904e97050ac6991dd7c9f80f17/src/commands/config/flowConfig.ml#L121-L137), although I have no idea how any of that works.

**Comment by ndbroadbent** [comment]
Woohoo, I figured it out! It's [the `module.file_ext` option](https://flow.org/en/docs/config/options/#toc-module-file-ext-string).

I fixed it by added the following lines to `.flowconfig`, under the `[options]` section:

```
[options]

; Extensions
module.file_ext=.js
module.file_ext=.jsx
module.file_ext=.json
module.file_ext=.css
module.file_ext=.scss
```

**Comment by skovhus** [comment]
Nice! 

@ndbroadbent are you up for creating a pull request for the README in this project?

Maybe also mention that `css-module-flow` should not be used together with `css-modules-flow-types`. `css-module-flow` just creates a dummy object without any flow checking.

**Comment by skovhus** [comment]
The README had been updated. Thanks : )

https://github.com/skovhus/css-modules-flow-types#support-for-other-file-extensions
