### ISSUE TITLE
[Feature Request] Silent mode

### ISSUE THREAD

**Issue by Ragnar-H** [skovhus/css-modules-flow-types#4]
### Use case
Using `css-modules-flow-types` with [pre-commit](https://github.com/observing/pre-commit) generates a lot of noise.

### Request
`css-modules-flow-types` should have a silent mode to not be so verbose

**Comment by skovhus** [comment]
Yeah, either we add `--verbose` or a `--silent` flag.

I think verbose mode is a good default to make it clear what the tool is doing.

So let us go with a `--silent` flag. 👍

**Comment by skovhus** [comment]
Thanks for contributing!

Released as 1.1.0. 🏅
